### ISSUE TITLE
Please update to support latest Swrve SDK (7.0.1)

### ISSUE THREAD

**Issue by nickvasic** [Swrve/swrve-react-native-sdk#10]
Currently the podspec for both, the react-native-swrve-plugin and react-native-swrve-geo plugin only support 

  s.dependency "SwrveGeoSDK", "4.1.0"
  s.dependency "SwrveSDKCommon", "6.8.1"
  s.dependency "SwrveSDK", "6.8.1"

We are having some trouble compiling the code on M1 (silicon) device in xcode 12.5 with the current dependency set.

**Comment by adam-govan** [comment]
hi @nickvasic, we will have the dependencies updated as part of our next release which is currently being worked on. We'll respond to this thread when it's out. With regards to the problem you're having, is it related to arch64 at all? and if you are using the latest Cocoapods could you send on the compilation error and any other information you think might be relevant / useful for debugging? 

thank you!

**Comment by nickvasic** [comment]
Thanks Adam, let us investigate more on our side. I'll get back to you with a bit more information. Thanks.

**Comment by nickvasic** [comment]
It seems like the main issue is the following error:

ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/sandy/Desktop/Arcbs/donor-react-native/ios/Pods/SwrveGeoSDK/SwrveGeoSDK.framework/SwrveGeoSDK' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Xcode 12.5.1
cocapods >>> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods.rb

**Comment by adam-govan** [comment]
hi @nickvasic, 
Yesterday, we've released a new version of the React Native Plugin. It introduces a few new features but as part of the workload we've updated out native dependencies to the current latest version of the SDKs. (iOS 7.0.1 , iOS 8.0.0). 

It's a major version update so you may need to change some small parts of your integration. I'll link our [Upgrade Guide](https://docs.swrve.com/release-notes/upgrade-guides/react-native-sdk-upgrade-guide/) here to help you out. 

Hopefully that resolves your issue. If it doesn't please respond to this and we'll continue to investigate.
