### ISSUE TITLE
Swrve sdk doesn't track events on init Manage Mode in Android

### ISSUE THREAD

**Issue by ims7inc** [Swrve/swrve-react-native-sdk#9]
When i start Swrve sdk with init mode my events are not tracking under QA Devices

IOS is working fine i am getting issue with Android

    //code added in onCreate method of MainApplication.java

    swrveConfig.setInitMode(SwrveInitMode.MANAGED);
    swrveConfig.setManagedModeAutoStartLastUser(false);

**Comment by KevBrodigan** [comment]
@ims7inc We had a look there on our latest version and couldn't replicate the issue you are seeing, after calling SwrveSDK.start('TestUser').  We could see QA events coming through.

It may be best to create a support ticket by emailing support@swrve.com so our support team can help debug this issue further.

Thanks,
Kevin
